<a href="https://colab.research.google.com/github/IlianRodriguez/Topicos-especiales-II/blob/main/Laboratorios/Laboratorio2/Laboratorio2_IlianRodriguez.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Laboratorio 2**
**Ilian Rodriguez (8-994-2383)**  
**07/09/2026**

1.	Descargue el siguiente Dataset: https://www.kaggle.com/datasets/datatalesbyagos/retail-hardware-salesventas-ferreteria

In [1]:
import pandas as pd #importo libreria pandas
url = "https://github.com/IlianRodriguez/Topicos-especiales-II/raw/refs/heads/main/Laboratorios/Laboratorio2/retail_ferreteria.csv" #url del csv
df = pd.read_csv(url, encoding="cp1252") #leo el csv y lo guardo en un dataframe inicial

2.	Realice el análisis exploratorio (columns, dtypes, head, describe)

In [2]:
print("---------- (1. Columnas del DataFrame) ----------")
display(df.columns.to_frame(index=False, name="Nombre de la columna"))#columns: obtiene los nombres de las columnas. to_frame: convierte el resultado en un DataFrame

print("\n---------- (2. Tipos de datos de las columnas del DataFrame) ----------")
display(df.dtypes.to_frame(name="Tipo de dato"))#dtypes: obtine el tipo de datos de cada columna. to_frame: convierte el resultado en un DataFrame

print("\n---------- (3. Primeras 5 filas del DataFrame) ----------")
display(df.head())#head: muestra las primeras 5 filas de cada columna

print("\n---------- (4. Primeras 5 filas del DataFrame) ----------")
display(df.describe())#describe: Obtener resumen estadistico

---------- (1. Columnas del DataFrame) ----------

   Nombre de la columna
0              id_venta
1            id_cliente
2        nombre_cliente
3              sucursal
4             provincia
5            fecha_hora
6              producto
7             categoria
8              cantidad
9       precio_unitario
10          total_venta
11           medio_pago
12       promo_producto
13           promo_pago
14      otros_productos

---------- (2. Tipos de datos de las columnas del DataFrame) ----------

                Tipo de dato
id_venta               int64
id_cliente             int64
nombre_cliente        object
sucursal              object
provincia             object
fecha_hora            object
producto              object
categoria             object
cantidad             float64
precio_unitario      float64
total_venta          float64
medio_pago            object
promo_producto        object
promo_pago            object
otros_productos       object

---------- (3. Primeras 5 filas del DataFrame) ----------

,id_venta,id_cliente,nombre_cliente,sucursal,provincia,fecha_hora,producto,categoria,cantidad,precio_unitario,total_venta,medio_pago,promo_producto,promo_pago,otros_productos
0,1,2824,Benjamin Perez Diaz,Sucursal Palermo,Buenos Aires,2025-06-29 12:36:14,Caja de tornillos,Fijaciones,2.0,11937.33,23874.66,mercadopago,NaN,NaN,NaN
1,2,2424,Amparo Paez Rodriguez,Sucursal Mendoza,Mendoza,2025-02-27 08:47:28,Taladro elÃ©ctrico,Herramientas elÃ©ctricas,1.0,5591.07,5591.07,mercadopago,10% off,NaN,NaN
2,3,7873,Martina Diaz Gimenez,Sucursal CÃ³rdoba,CÃ³rdoba,2024-09-26 19:31:40,Sierra circular,Herramientas elÃ©ctricas,5.0,14631.34,73156.70,tarjeta_dÃ©bito,2x1,5% off efectivo,NaN
3,4,5552,Sr(a). Thiago Agustin Quiroga,Sucursal CÃ³rdoba,CÃ³rdoba,2025-02-26 10:24:10,Llave inglesa,Herramientas manuales,3.0,6008.30,18024.90,tarjeta_dÃ©bito,NaN,NaN,NaN
4,5,5333,TomÃ s Victoria Aguero,Sucursal Palermo,Buenos Aires,2025-07-08 04:47:31,Sierra circular,Herramientas elÃ©ctricas,5.0,7116.48,35582.40,mercadopago,NaN,NaN,NaN

---------- (4. Primeras 5 filas del DataFrame) ----------

          id_venta   id_cliente     cantidad  precio_unitario    total_venta
count  3150.000000  3150.000000  3091.000000      3090.000000    3150.000000
mean   1496.748254  5548.900317     2.958913     25305.972612   74201.774194
std     867.007861  2608.448100     1.414646     14340.903448   61493.871222
min       1.000000  1001.000000     1.000000      1004.520000 -220383.250000
25%     747.000000  3274.000000     2.000000     12830.680000   26785.890000
50%    1496.500000  5561.500000     3.000000     25149.000000   57516.340000
75%    2247.750000  7822.500000     4.000000     37813.882500  108729.555000
max    3000.000000  9991.000000     5.000000     49993.000000  249860.200000

3.	Análisis exploratorio inicial (shape, info, isna().sum(), duplicated())

In [11]:
print("---------- (1. Cantidad de filas y columnas del DataFrame) ----------")
print("Cantidad de filas del DataFrame: ",df.shape[0], "\nCantidad de columnas de DataFrame: ",df.shape[1])

---------- (1. Cantidad de filas y columnas del DataFrame) ----------
Cantidad de filas del DataFrame:  3150
Cantidad de columnas de DataFrame:  15